name: chef_upp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  
  # Core
  dio: ^4.0.4

  
  # Route
  auto_route: ^3.2.4
  
  # State Management
  flutter_bloc: ^8.0.1
  
  # UI Kit
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  feather_icons: ^1.2.0
  lottie: ^1.2.2
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.1.0
  simple_animations: ^4.0.1

  # Utils
  logger: ^1.1.0
  retry: ^3.1.0
  equatable: ^2.0.3
  


  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  auto_route_generator: ^3.2.3
  build_runner:
  mockito: ^5.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/launch_image.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:

    - assets/images/
